### ISSUE TITLE
Activation of dark moder

### ISSUE THREAD

**Issue by Aenardhil** [rdkit/rdkit-js#369]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I want to a activate dark mode or any type of dark background with the atom and bound with light colour.

**Describe alternatives you've considered**
I have tried to change the background colour to a dark blue with backgroundColour but the problem is that the bounds are indistinguishable. I've tried then to use svg instead of canvas to modify the colours using css but the carbons are not selectable by css selectors.

**Comment by MichelML** [comment]
@Aenardhil maybe @ptosco has a better idea here, but here's a starter "hack", in svg mode, you can make most bonds white like this (but you'll probably have to hack other things in the image like atom numbers, etc):

```css
# This means all path elements with a class starting with the word "bond"
# (ideally be more specific than that in your css selection
path[class^="bond"] {
    stroke: white !important;
    fill: white !important;
}

# set the svg background to black (ideally be more specific than that in your css selection)
svg {
    background-color: black;
}
```

example:

![image](https://github.com/rdkit/rdkit-js/assets/9539763/154de033-ef8d-4d04-9f62-81604ca5dd7a)
